id: PDB15BC75
initial_creation_type: input
source_metadata:
  title: Rigdzin Nyima Drakpa
  language: en
  description: 'Texts by and about the treasure-revealer Rigdzin Nyima Drakpa (rig
    ''dzin nyi ma grags pa, 1647–1710), alias Garwang Drodül Lingpa:'
  volume:
    e2d1cebbcead4bb594dcb197a89023a0:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Aspiration Prayers
created_at: '2022-03-01T01:22:35.007539'
last_modified_at: '2022-03-01T01:22:35.007545'
